### ISSUE TITLE
(Millimoles/Liters) and (Millimoles^1/Liters^1) are incompatible units

### ISSUE THREAD

**Issue by martamatos** [opencobra/MASS-Toolbox#38]
When loading a given model (BIOMD0000000064 in biomodels database) I get the following error:

![importteusink](https://cloud.githubusercontent.com/assets/609864/5777508/6bb69e3c-9d93-11e4-923f-9477ae65bb92.png)

After the error is raised Mathematica continues running the command for at least 1min (after that I aborted the evaluation).

**Comment by avsastry** [comment]
Apparently some SBML files (BIOMD0000000064) store units as Millimoles^1., instead of Millimoles^1, and the old parser had troubles turning the float into an integer. To fix this I had the parser round the exponents of the units, but would we ever come across units to a fractional power where this would screw up the import? (i.e. Meter^(1/2))
The fix is detailed in pull request https://github.com/opencobra/MASS-Toolbox/pull/41

**Comment by avsastry** [comment]
Undid the old fix and incorporated integerChop into Quantity
